const ACTIVE=new Set(["researcher","quant","investor","scientist","systems","skeptic","contrarian","observer","governance"]);
const PERSPECTIVES=[["researcher","RESEARCHER","Evidence-bound fundamental research"],["quant","QUANT","Quantitative and statistical interpretation"],["investor","INVESTOR","Investment thesis"],["scientist","SCIENTIST","Scientific and epistemic validity"],["systems","SYSTEMS","Systems risk"],["contrarian","CONTRARIAN","Strongest credible opposing case"],["skeptic","SKEPTIC","Evidence and assumption challenge"],["observer","OBSERVER","Outcome observation"],["governance","GOVERNANCE","CHARTER and authority boundary"]];
const STAGES=[
 ["opportunity","◇","OPPORTUNITY","Front door for an investment question" ,"active-analysis"],
 ["evidence","▤","EVIDENCE","Validated inputs and provenance" ,"evidence"],
 ["underwriting","▦","UNDERWRITING","CRE underwriting where supplied" ,"active-analysis"],
 ["perspectives","◌","PERSPECTIVES","Competing reasoning perspectives" ,"perspective-summary"],
 ["conflict","⇄","CONFLICT","Disagreement and horizon divergence" ,"conflict-intelligence"],
 ["risk","∿","INDEPENDENT RISK","Scenario simulation" ,"independent-risk"],
 ["contrarian","△","CONTRARIAN","Adversarial review" ,"perspective-summary"],
 ["case","▣","INVESTMENT CASE","Analytical case assembly" ,"investment-case"],
 ["gate","◇","DECISION GATE","Readiness boundary" ,"decision-gate"],
 ["observer","◉","OBSERVER","Real-world observation" ,"observer"],
 ["learning","✦","LEARNING","Outcome-derived institutional learning" ,"learning"]
];
let latestUnderwriting={};let latestAnalysis=null;let analysisRequestSequence=0;let memoryRecords=[];const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function listText(v,fallback="NOT AVAILABLE"){if(Array.isArray(v))return v.length?v.join(" • "):fallback;return v==null||v===""?fallback:String(v);}
function riskText(v,fallback="NOT AVAILABLE"){if(Array.isArray(v))return v.length?`${v.length} concern${v.length===1?"":"s"}`:"NONE IDENTIFIED";return v==null||v===""?fallback:String(v);}
function errorText(data,fallback="Analysis failed"){const d=data?.detail;if(typeof d==="string"&&d.trim())return d;if(Array.isArray(d))return d.map(x=>`${Array.isArray(x?.loc)?x.loc.join("."):"request"}: ${x?.msg||"validation error"}`).join(" • ")||fallback;if(d&&typeof d==="object"){if(typeof d.message==="string")return d.message;try{return JSON.stringify(d);}catch{return fallback;}}return fallback;}
function openDrawer(){const d=$("command-drawer");d.classList.add("open");d.setAttribute("aria-hidden","false");setTimeout(()=>$("question")?.focus(),50);}
function closeDrawer(){const d=$("command-drawer");d.classList.remove("open");d.setAttribute("aria-hidden","true");}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});}
function renderPipeline(states={}){$("pipeline-stages").innerHTML=STAGES.map(([id,icon,name,desc,target],i)=>{const s=states[id]||{status:"NOT RUN",tone:""};return `<button class="stage ${s.current?"current":""}" data-target="${target}" data-stage="${id}"><div class="stage-icon">${icon}</div><div class="stage-num">${String(i+1).padStart(2,"0")}</div><div class="stage-name">${name}</div><div class="stage-status ${s.tone||""}">${esc(s.status)}</div><div class="stage-desc">${esc(desc)}</div></button>`}).join("");document.querySelectorAll(".stage").forEach(x=>x.addEventListener("click",()=>scrollToId(x.dataset.target)));}
function defaultPipeline(){renderPipeline({opportunity:{status:"READY",tone:"good"},evidence:{status:"NOT RUN"},underwriting:{status:"INPUTS",tone:"warn"},perspectives:{status:"NOT RUN"},conflict:{status:"NO DATA"},risk:{status:"NOT RUN"},contrarian:{status:"NOT RUN"},case:{status:"NOT RUN"},gate:{status:"CLOSED"},observer:{status:"RECORDED",tone:"good"},learning:{status:"OUTCOME-DEPENDENT",tone:"warn"}});}
function renderPerspectives(outputs=[]){const byId=Object.fromEntries(outputs.map(x=>[x.agent_id||x.agent?.agent_id,x]));$("perspectives").innerHTML=PERSPECTIVES.map(([id,name,detail])=>{const active=ACTIVE.has(id),out=byId[id],status=active?(out?"RETURNED":"ACTIVE"):"NOT YET ACTIVE",signal=out?.direction||out?.recommendation||detail;return `<article class="agent ${active?"active":"inactive"}" data-perspective="${id}" tabindex="0"><div class="agent-name"><span>${name}</span><span class="agent-status">${status}</span></div><div class="agent-detail">${esc(signal)}</div></article>`}).join("");document.querySelectorAll(".agent").forEach(card=>{const show=()=>inspectPerspective(byId[card.dataset.perspective],card.dataset.perspective);card.addEventListener("click",show);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();show();}});});if(outputs.length)inspectPerspective(outputs[0],outputs[0].agent_id);}
function inspectPerspective(out,id){document.querySelectorAll(".agent").forEach(x=>x.classList.toggle("selected",x.dataset.perspective===id));const meta=PERSPECTIVES.find(x=>x[0]===id)||[id,String(id).toUpperCase(),""];const box=$("perspective-inspector");if(!out){box.innerHTML=`<span class="field-label">PERSPECTIVE INSPECTOR</span><strong>${esc(meta[1])}</strong><p>Active perspective, but no returned output is available for this analysis.</p>`;return;}const text=out.analysis||out.summary||out.reasoning||out.rationale||out.conclusion||out.direction||"Returned output available; detailed field not supplied.";box.innerHTML=`<span class="field-label">PERSPECTIVE INSPECTOR / ${esc(meta[1])}</span><strong>${esc(out.direction||out.recommendation||"RETURNED")}</strong><p>${esc(text)}</p>`;}
function renderMeta(meta={}){const has=meta&&typeof meta==="object"&&Object.keys(meta).length>0;$("learning-state").textContent=has?"PROCESS EVALUATED":"INSUFFICIENT DATA";$("learning-detail").textContent=has?"Meta-Intelligence evaluates the reasoning process; it is not a directional vote or authority.":"Calibration and outcome-derived learning should not be fabricated before sufficient resolved outcomes exist.";}
function setDecision(v){const raw=String(v||"NO DATA");$("memory-decision").textContent=raw;}
function renderConflicts(conflicts=[],horizon=[]){const items=[...(Array.isArray(conflicts)?conflicts:[]),...(Array.isArray(horizon)?horizon:[])];$("conflict-count").textContent=`${items.length} ${items.length===1?"ITEM":"ITEMS"}`;$("conflicts").innerHTML=items.length?items.map(c=>{const r=c?.conflict_record&&typeof c.conflict_record==="object"?c.conflict_record:c||{};const q=Array.isArray(r.unresolved_questions)?r.unresolved_questions.join(" • "):r.unresolved_questions||c.description||"Unresolved question not supplied.";return `<div class="conflict-item"><strong>${esc(r.conflict_type||c.type||"CONFLICT")}</strong><span>${esc(r.severity||c.severity||"UNSPECIFIED")}</span><div class="question">${esc(q)}</div></div>`}).join(""):"NO CONFLICT DATA / NO DISAGREEMENT RETURNED";}
function renderRisk(sim={}){const scenarios=Array.isArray(sim.scenarios)?Object.fromEntries(sim.scenarios.map(x=>[String(x.scenario).toLowerCase(),x])):(sim.scenarios||{});const names=["base","bull","bear","adversarial"];$("risk-grid").innerHTML=names.map(n=>{const x=scenarios[n];if(!x)return `<div class="risk-card"><span>${n.toUpperCase()}</span><strong>NO DATA</strong><em>Backend metric not returned</em></div>`;return `<div class="risk-card"><span>${n.toUpperCase()}</span><strong>${esc(x.mean_terminal??"NOT AVAILABLE")}</strong><em>loss ${x.probability_loss==null?"NOT AVAILABLE":esc(x.probability_loss)} • drawdown ${x.max_drawdown_mean==null?"NOT AVAILABLE":esc(x.max_drawdown_mean)}</em></div>`}).join("");$("risk-note").textContent=sim.independent_of_agents===false?"INDEPENDENCE FLAG FAILED":"Independent simulation output. Agent conclusions do not determine these results.";}
function renderUnderwriting(data={}){latestUnderwriting=data||{};const m=data.metrics||{};$("active-underwriting").textContent=(data.status||"NOT AVAILABLE").replaceAll("_"," ");$("memory-why").textContent=m.noi==null?"NOT AVAILABLE":`NOI ${fmtMoney(m.noi)}`;}
function fmtMoney(v){return v==null?"NOT AVAILABLE":new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(v);}
function renderGate(gate={},readiness={}){const state=String(gate.state||"CLOSED").replaceAll("_"," ");const ready=gate.ready_for_human_authority===true;$("gate-state").textContent=ready?"OPEN":"CLOSED";$("gate-substate").textContent=ready?"READY FOR HUMAN AUTHORITY":state;$("active-gate").textContent=state;$("gate-evidence").textContent=`${gate.evidence_status?.count??0} VALIDATED / ${gate.evidence_status?.usable_count??0} USABLE`;$("gate-conflict").textContent=gate.unresolved_conflicts?.length?`${gate.unresolved_conflicts.length} UNRESOLVED":"NONE`;$("gate-risk").textContent=gate.independent_risk?.valid===false?"INVALID":gate.independent_risk?"RETURNED":"NO DATA";$("gate-contrarian").textContent=gate.contrarian_review_status||"NOT AVAILABLE";const stops=gate.hard_stops||[];$("hard-stops").textContent=stops.length?stops.join(" • "):"NONE RETURNED";$("gate-state").style.color=ready?"var(--green)":"var(--amber)";}
function renderActive(data){latestAnalysis=data;const evidence=data.evidence||{},agents=data.agents||[],conflicts=[...(data.conflicts||[]),...(data.horizon_divergences||[])],sim=data.simulation||{},gate=data.decision_gate||{},caseData=data.institutional_investment_case||{},readiness=data.decision_readiness||{};$("active-question").textContent=data.question||"No analysis selected";$("active-opportunity").textContent=[data.research_context?.asset,data.research_context?.market].filter(Boolean).join(" • ")||"NOT SUPPLIED";$("active-evidence").textContent=`${evidence.count??0} VALIDATED / ${evidence.usable_count??0} USABLE`;$("active-perspectives").textContent=agents.length?`${agents.length} RETURNED":"NOT RUN";$("active-conflict").textContent=conflicts.length?`${conflicts.length} ITEMS":"NO DATA";$("active-risk").textContent=Object.keys(sim.scenarios||{}).length?"RETURNED":"NO DATA";$("active-contrarian").textContent=data.skeptic?.valid===false?"INVALID":data.skeptic?"RETURNED":"NOT RUN";$("active-case").textContent=caseData.status||readiness.status||"AVAILABLE";$("research-state").textContent="COMPLETE";$("research-state").className="state-badge operational";setDecision(data.synthesis?.verdict);renderPerspectives(agents);renderMeta(data.meta_intelligence||{});renderConflicts(data.conflicts||[],data.horizon_divergences||[]);renderRisk(sim);renderGate(gate,readiness);$("memory-belief").textContent=data.question||"NOT AVAILABLE";$("memory-decision").textContent=data.synthesis?.verdict||"NOT AVAILABLE";$("memory-outcome").textContent=data.observer?.status||"PENDING";const stages={opportunity:{status:"ACTIVE",tone:"good",current:true},evidence:{status:evidence.usable_count?`${evidence.usable_count} USABLE`:"NO DATA",tone:evidence.usable_count?"good":"warn"},underwriting:{status:latestUnderwriting.status?String(latestUnderwriting.status).replaceAll("_"," "):"NOT RUN"},perspectives:{status:agents.length?`${agents.length} RETURNED`:"NO DATA",tone:agents.length?"good":"warn"},conflict:{status:conflicts.length?`${conflicts.length} ITEMS":"NONE",tone:conflicts.length?"warn":"good"},risk:{status:Object.keys(sim.scenarios||{}).length?"RETURNED":"NO DATA",tone:Object.keys(sim.scenarios||{}).length?"good":"warn"},contrarian:{status:data.skeptic?"RETURNED":"NO DATA"},case:{status:caseData.status||readiness.status||"AVAILABLE"},gate:{status:gate.ready_for_human_authority?"READY FOR HUMAN":"CLOSED",tone:gate.ready_for_human_authority?"good":"warn"},observer:{status:data.observer?"RETURNED":"NO DATA"},learning:{status:(data.institutional_learning?.lessons||[]).length?"LESSONS":"INSUFFICIENT DATA",tone:"warn"}};renderPipeline(stages);}
function clearAnalysisOutputs(){$("active-question").textContent="Running new analysis…";$("active-evidence").textContent="0 VALIDATED / 0 USABLE";$("active-perspectives").textContent="NOT RUN";$("active-conflict").textContent="NO DATA";$("active-risk").textContent="NOT RUN";$("active-contrarian").textContent="NOT RUN";$("active-case").textContent="NOT AVAILABLE";$("active-gate").textContent="CLOSED / NO DATA";renderPerspectives([]);renderConflicts([],[]);renderRisk({scenarios:[]});renderGate({});}
async function runAnalysis(e){e.preventDefault();const requestId=++analysisRequestSequence,b=$("run-button");b.disabled=true;b.textContent="RUNNING RESEARCH ANALYSIS…";clearAnalysisOutputs();const question=$("question").value.trim(),asset=$("asset").value.trim(),market=$("market").value.trim(),initialValue=Number($("initial-value").value),horizonSteps=Number($("horizon").value),paths=Number($("paths").value);if(!question){b.disabled=false;b.textContent="RUN RESEARCH ANALYSIS";return;}if(!Number.isFinite(initialValue)||initialValue<=0||!Number.isInteger(horizonSteps)||horizonSteps<1||!Number.isInteger(paths)||paths<100){$("research-state").textContent="ERROR";b.disabled=false;b.textContent="RUN RESEARCH ANALYSIS";return;}try{const r=await fetch("/analysis/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,evidence:[],asset,market,cre_underwriting:latestUnderwriting,initial_value:initialValue,horizon_steps:horizonSteps,paths,seed:42})});const data=await r.json();if(requestId!==analysisRequestSequence)return;if(!r.ok)throw Error(errorText(data));renderActive(data);await loadMemory();await loadLearning();closeDrawer();scrollToId("active-analysis");}catch(err){if(requestId!==analysisRequestSequence)return;$("research-state").textContent="ERROR";$("active-question").textContent=err.message||"Analysis failed";}finally{if(requestId===analysisRequestSequence){b.disabled=false;b.textContent="RUN RESEARCH ANALYSIS";}}
}
async function loadCapitalManifest(){try{const r=await fetch("/capital/manifest");if(!r.ok)throw Error();const data=await r.json();const domains=Array.isArray(data.research_domains)?data.research_domains:[];$("capital-domain-status").textContent=domains.length?"RESEARCH DOMAINS EXPOSED":"RESEARCH INTELLIGENCE";}catch{$("capital-domain-status").textContent="MANIFEST UNAVAILABLE";}}
async function health(){try{const r=await fetch("/health");if(!r.ok)throw Error();const data=await r.json();$("api-dot").className="status-dot online";$("api-status").textContent=data.live_market_data?"API ONLINE • MARKET DATA LIVE":"API ONLINE";$("sys-api").textContent="ONLINE";$("sys-api").className="good";}catch{$("api-dot").className="status-dot offline";$("api-status").textContent="API UNAVAILABLE";$("sys-api").textContent="UNAVAILABLE";}}
function renderRecent(records=[]){memoryRecords=records;const items=records.slice(-8).reverse();$("recent-analyses").innerHTML=items.length?items.map((r,i)=>`<div class="recent-item" data-record="${records.length-1-i}"><strong>${esc(r.question||"Untitled analysis")}</strong><span>${esc(r.synthesis?.verdict||r.record_type||"RECORDED")} • ${esc(r.timestamp||r.created_at||"recorded")}</span></div>`).join(""):"<div class=\"empty-state\">NO ANALYSES RECORDED</div>";document.querySelectorAll(".recent-item").forEach(x=>x.addEventListener("click",()=>{const r=memoryRecords[Number(x.dataset.record)];if(r?.question){$("question").value=r.question;scrollToId("active-analysis");}}));}
function renderMemory(records=[]){renderRecent(records);const r=records.at(-1);if(!r)return;$("memory-belief").textContent=r.question||"NOT AVAILABLE";$("memory-why").textContent=r.evidence?.count==null?"NOT AVAILABLE":`${r.evidence.count} evidence item(s)`;$("memory-decision").textContent=r.synthesis?.verdict||"NOT AVAILABLE";$("memory-outcome").textContent=r.outcome?.status||r.observer?.status||"PENDING";$("memory-lesson").textContent=r.lesson||"AWAITING OUTCOME";}
async function loadMemory(){try{const r=await fetch("/memory");if(!r.ok)throw Error();const data=await r.json();renderMemory(data.records||[]);}catch{$("recent-analyses").innerHTML="<div class=\"empty-state\">MEMORY UNAVAILABLE</div>";}}
async function loadLearning(){try{const r=await fetch("/observer/learning",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bins:10})});if(!r.ok)throw Error();const data=await r.json();if(Array.isArray(data.lessons)&&data.lessons.length){$("learning-state").textContent="LESSONS AVAILABLE";$("learning-lessons").textContent=data.lessons.join(" • ");}else{$("learning-state").textContent="INSUFFICIENT DATA";$('learning-lessons').textContent="AWAITING OUTCOME";}}catch{$("learning-state").textContent="INSUFFICIENT DATA";$("learning-lessons").textContent="AWAITING OUTCOME";}}
function wireNavigation(){document.querySelectorAll(".nav-item:not(.disabled)").forEach(a=>a.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));a.classList.add("active");}));$("new-analysis")?.addEventListener("click",openDrawer);$("new-analysis-top")?.addEventListener("click",openDrawer);$("close-drawer")?.addEventListener("click",closeDrawer);$("analysis-form")?.addEventListener("submit",runAnalysis);$("open-analysis")?.addEventListener("click",()=>scrollToId("active-analysis"));$("open-simulation")?.addEventListener("click",()=>scrollToId("independent-risk"));$("open-learning")?.addEventListener("click",()=>scrollToId("learning"));$("view-conflicts")?.addEventListener("click",()=>scrollToId("conflict-intelligence"));$("view-gate-details")?.addEventListener("click",()=>scrollToId("decision-gate"));$("load-memory")?.addEventListener("click",()=>{loadMemory();loadLearning();});$("global-search")?.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const q=e.currentTarget.value.trim().toLowerCase();if(!q)return;const hit=[...document.querySelectorAll(".nav-item,.panel")].find(x=>x.textContent.toLowerCase().includes(q));if(hit){hit.scrollIntoView({behavior:"smooth",block:"start"});e.currentTarget.blur();}});}
defaultPipeline();renderPerspectives();renderConflicts();renderRisk();renderGate({});renderUnderwriting();wireNavigation();health();loadCapitalManifest();loadMemory();loadLearning();